"""add votes table using autogenerate command

Revision ID: 11ea5268c8b1
Revises: ebbc8acc36b0
Create Date: 2026-02-28 22:12:54.434140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ea5268c8b1'
down_revision: Union[str, Sequence[str], None] = 'ebbc8acc36b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
